name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1
      - name: Build static Catalog
        run: |
          sudo apt install -y proj-bin libproj-dev
          pip install open-science-catalog-builder/
          osc build data/ -o dist/ \
            --root-href "https://constantinius.github.io/osc-demo/"
      - name: Copying Catalog client
        run: |
          cp -r client/* dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
